# Site settings
author: Nicholas Rozmus
title: College vs. Coding Bootcamps, The Opportunity Epiphany.
header-img: img/home-bg.png
email: rozmusnicholas@gmail.com
copyright_name: Nicholas Rozmus
description: > # this means to ignore newlines until "baseurl:"
  Breaking Mainstream Education For A Shot At The American Dream.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nrozmus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
